### ISSUE TITLE
Monitor info.configuration is undefined

### ISSUE THREAD

**Issue by ahoyahoy** [ueberdosis/hocuspocus#638]
>  BTW where the source code of the Monitor from the multirepo disappeared?

Monitor dashboard doesn't run for us.
The error is in Info.vue component on code `info.configuration.name`
` Cannot read properties of undefined (reading 'name')`

package.js
```
"@hocuspocus/extension-monitor": "^2.0.1",
"@hocuspocus/extension-redis": "^2.1.0",
"@hocuspocus/server": "^2.1.0",

```

setup:
```
const monitor = new Monitor({
  dashboardPath: 'dashboard',
  enableDashboard: true,
  metricsInterval: 10000,
  osMetricsInterval: 10000,
  port: null,
  password: ...,
  user: ...,
})

const server = Server.configure({
  async onAuthenticate(data) { ... },

  extensions: [
	new Redis(...),
	monitor,
  ],

  name: 'XYZ'
})
```

**Comment by janthurau** [comment]
hey @ahoyahoy, we've removed extension-monitor from the repo (and stopped maintaining it) because it depended on so many old libraries that it would require a rewrite, but on the other hand was/is used only by a handful of companies. The source code is still available in the history in case you want to have look (commit id of removal: 35afa5c09efa396d8cc869a118945d094dc47b63)

**If you haven't used it before, you shouldn't start using it now.**

**Comment by ahoyahoy** [comment]
Hi @janthurau 
thanks
we used it for version 1
is there a roadmap or is it completely outside the priorities
will it ever go back to the public repo?
