### ISSUE TITLE
Many operations to disconnect/destroy

### ISSUE THREAD

**Issue by linspw** [ueberdosis/hocuspocus#642]
**Description**
After some changes and page changes I noticed that provider was still connected, that's because a destroy was missing in the unmounted of the page.

However, it was necessary to perform several operations:

```ts

onBeforeUnmount(() => {
  provider?.configuration?.websocketProvider?.webSocket?.close()
  provider?.configuration?.websocketProvider.destroy()
  provider?.destroy()
})
```

In yjs provider only destroy is enough.
Anyway, it's a simple problem and I thank you in advance for your attention.

**Steps to reproduce the bug**
- Change page with active connection

**Expected behavior**
Wouldn't the ideal behavior be just to do `provider?.destroy()`?

**Screenshot, video, or GIF**
-
**Environment?**
 - operating system: Linux
 - browser: Chrome
 - mobile/desktop: Desktop
 - Hocuspocus version:"@hocuspocus/provider": "^2.0.6"

**Additional context**
- Nuxt 3
- Vue

**Comment by janthurau** [comment]
Hey @linspw,

`provider?.configuration?.websocketProvider?.webSocket?.close()` should not be necessary, as the providerWebsocket will terminate the websocket on destroy.

You indeed need to destroy both the provider and the websocketProvider atm, which is by intention because you might want to reuse the socket connection for another provider :)

**Comment by linspw** [comment]
Perfect, what you said makes sense, thanks  @janthurau !
I'll adjust here....
