### ISSUE TITLE
onStoreDocument only store the combined updates 

### ISSUE THREAD

**Issue by websiddu** [ueberdosis/hocuspocus#646]
Seems like with Houcuspocus, you have to store the whole document when using the `onStoreDocument` hook, this is not scalable if want to store and maintain version history. 

I can use "onChange" hook and store every change, however that is not very scalable either. 

And ideal solution would be to merge the updates using the debounce time and then passing them to the `onStoreDocument` hook. Like suggested in this [post](https://discuss.yjs.dev/t/y-websocket-debounce-broadcast-and-merge-updates/885)

**Comment by janthurau** [comment]
not sure I get what you want to see here, the onStoreDocument hook needs to store the entire document - otherwise, it would not be available on the next start of the server.

The discussion that you linked is about debouncing on the provider side, so that changes are sent to the server in a grouped way (currently each change is sent immediately and separately), we already have a feature request about this: #292.

Let me know if I misunderstood you, but I think you want #292 :)

**Comment by websiddu** [comment]
So, if you want to store version history, one will want to store all the updates, but storing every update is not really efficient, so the request was to make a large, merged update available in the onStoreDocument as this is throttled already. 

So, this way we can store the updates and rewind back in time for version history. 

Currently this possible by creating a updateCache array and add all the updates to the updateCache until the onStoreDocument, during storage merge these updates into one, and store it, and reset the updateCache. The above seems little bit flakey as you could never know if the cache is reset when new set of updates are ready. 

So wondering if there is a better way to handle this directly in the library.

**Comment by ZhangMingZhao1** [comment]
> So, if you want to store version history, one will want to store all the updates, but storing every update is not really efficient, so the request was to make a large, merged update available in the onStoreDocument as this is throttled already.
> 
> So, this way we can store the updates and rewind back in time for version history.
> 
> Currently this possible by creating a updateCache array and add all the updates to the updateCache until the onStoreDocument, during storage merge these updates into one, and store it, and reset the updateCache. The above seems little bit flakey as you could never know if the cache is reset when new set of updates are ready.
> 
> So wondering if there is a better way to handle this directly in the library.

I had the same problem. Did you solve it? And I have a new problem now, that is the onLoadDocument method of hocus also triggers the onChange method once when it executes, which causes my onChange to store a big complete document update. how can I distinguish in the onChange method if it's an incremental change or if it's due to the first time the document is loaded? How can I tell in the onChange method if the change is incremental or triggered by the first loading of the document?

Translated with DeepL.com (free version)

**Comment by ZhangMingZhao1** [comment]
> So, if you want to store version history, one will want to store all the updates, but storing every update is not really efficient, so the request was to make a large, merged update available in the onStoreDocument as this is throttled already.
> 
> So, this way we can store the updates and rewind back in time for version history.
> 
> Currently this possible by creating a updateCache array and add all the updates to the updateCache until the onStoreDocument, during storage merge these updates into one, and store it, and reset the updateCache. The above seems little bit flakey as you could never know if the cache is reset when new set of updates are ready.
> 
> So wondering if there is a better way to handle this directly in the library.

I had the same problem. Did you solve it? And I have a new problem now, that is the onLoadDocument method of hocus also triggers the onChange method once when it executes, which causes my onChange to store a big complete document update. how can I distinguish in the onChange method if it's an incremental change or if it's due to the first time the document is loaded? How can I tell in the onChange method if the change is incremental or triggered by the first loading of the document?
