### ISSUE TITLE
`getDocumentName` config option does not work

### ISSUE THREAD

**Issue by ImSingee** [ueberdosis/hocuspocus#687]
**Description**

It still appears in the typescript definition, but not works at all (I can't find any reference to it in the code).

**Additional context**

Seems #262 is merged, but reverted in some time

**Comment by ImSingee** [comment]
@janthurau I want to hide the actual documentName from the client side (dynamically assign the documentName based on user info). Is there any way to do some similar things in `onAuthenticated`?

**Comment by janthurau** [comment]
somehow I missed this - sorry!

The easiest would be to just handle this in the database connection, so i.e. fetch method of extension-database.

**Comment by kroyee** [comment]
What if my use-case it that I want client A to connect to my server with `documentName: foo` and client B to connect to my server with `documentName: bar` but they should share the document.

If I'm not mistaken, loading the same document from the database would mean they start with the same document but they would not be connected to each other as far as the server is concerned, so updates between the clients would not happen in real-time?

I do this because i use part of the URL path to determine the document name, but sometime I want to give it a shorter easier-to-remember name.

So exampleurl.com/674583567843625798 and exampleurl.com/simple should refer to the same document.

I could make a request and check before I connect, but before I just handled this in hocuspocus server, which was convenient.
