### ISSUE TITLE
handleDocumentUpdate does not check if connection is valid correctly

### ISSUE THREAD

**Issue by matthew-akuhata** [ueberdosis/hocuspocus#730]
**Description**

It looks like [this change](https://github.com/ueberdosis/hocuspocus/pull/696) caused other instances of `Hocuspocus` server to trigger onStoreDocument when a change is communicated via the `redis` extension. There's no context or connection when that happens, since the 'connection' is a `string` and not of class `Connection`

**Steps to reproduce the bug**
1. Create Multiple instances of `Hocuspocus` Servers communicating with the `redis` extension
2. Two client connect to different instances of `Hocuspocus` Server
3. Make an edit on a client 1, client 2 debounce is triggered without a connection or context.

**Expected behavior**

During [handleDocumentUpdate](https://github.com/ueberdosis/hocuspocus/blob/main/packages/server/src/Hocuspocus.ts#L377) we should check if the connection is an instance of Connection and a connection and context should be passed through.
```
    if (!(connection instanceof Connection)) {
      return
    }
```

**Additional context**

[PR that caused this issue](https://github.com/ueberdosis/hocuspocus/pull/696)
[Where change should be made](https://github.com/ueberdosis/hocuspocus/blob/main/packages/server/src/Hocuspocus.ts#L377)

**Comment by janthurau** [comment]
hmm, shit, that was unintended. Good catch!

What kind of issues does this create for you? The redis extension should anyway lock the onStoreDocument hooks, and when thinking longer about this it actually looks like it's a good idea to store to database on any change, regardless of whether it's incoming from the provider or from some local extension 🤔  I can only imagine that you do something with the context in onStoreDocument, and this now fails because on server2 the context does not exist?

**Comment by janthurau** [comment]
I've just release a patch release to revert this back to the old behaviour, by excluding the special 'redis' origin. Thanks for the report and sorry for the trouble!
